from micropython import const

PROTOCOL_FLAG_READING_AVAILABLE = const(1 << 0)
PROTOCOL_FLAG_BATTERY_LOW = const(1 << 1)

PROTOCOL_T1_READING_LEN = const(5)
PROTOCOL_LEXI_READING_LEN = const(6)
PROTOCOL_MAX_READING_LEN = const(32)

PROTOCOL_T1_MODE_NO_TRIGGER = const(0)
PROTOCOL_T1_MODE_TRIGGER = const(1)
PROTOCOL_T1_MODE_TRACKING = const(2)
PROTOCOL_T1_MODE_MIN_MAX = const(3)


# request types

E_PROTOCOL_GET_STATUS = const(0)
E_PROTOCOL_GET_DEVICE_INFO = const(1)
E_PROTOCOL_UPDATE_TIME = const(2)
E_PROTOCOL_UPDATE_SETTINGS = const(3)
E_PROTOCOL_GET_READING = const(4)
E_PROTOCOL_ENTER_BOOTLOADER = const(5)
E_PROTOCOL_SET_UNIQUE_ID = const(6)
E_PROTOCOL_GET_SETTINGS = const(7)
E_PROTOCOL_GO_TO_SLEEP = const(8)
E_PROTOCOL_CALIBRATE = const(9)
E_PROTOCOL_READ_FW = const(10)
E_PROTOCOL_GET_MIN_READING = const(11)
E_PROTOCOL_GET_MAX_READING = const(12)


# result types

E_PROTOCOL_RESULT_SUCCESS = const(0)
E_PROTOCOL_RESULT_INVALID_PARAMS = const(1)
E_PROTOCOL_RESULT_FAILED = const(2)


PROTOCOL_REQUEST_HEADER_FORMAT = '<BI'

PROTOCOL_RESPONSE_HEADER_FORMAT = '<BI'
PROTOCOL_RESPONSE_DEV_INFO_FORMAT = '<BBBBBBBBBBBHb'
PROTOCOL_RESPONSE_READING_T1_FORMAT = '<fB'
